export const ERROR_CODES = Object.freeze({
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  INVALID_STATE: "INVALID_STATE",
  CONFLICT: "CONFLICT",
  DUPLICATE: "DUPLICATE",
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  STALE_VERSION: "STALE_VERSION",
  SETUP_REQUIRED: "SETUP_REQUIRED"
});
