export const SNAPSHOT_ERROR_CODES = Object.freeze({
  SNAPSHOT_NOT_FOUND: "SNAPSHOT_NOT_FOUND",
  SNAPSHOT_INVALID_STATE: "SNAPSHOT_INVALID_STATE",
  SNAPSHOT_STALE: "SNAPSHOT_STALE",
  SNAPSHOT_SCHEMA_UNSUPPORTED: "SNAPSHOT_SCHEMA_UNSUPPORTED",
  SNAPSHOT_METADATA_REQUIRED: "SNAPSHOT_METADATA_REQUIRED",
  SNAPSHOT_BOOTSTRAP_FORBIDDEN: "SNAPSHOT_BOOTSTRAP_FORBIDDEN",
  SNAPSHOT_ROW_COUNT_MISMATCH: "SNAPSHOT_ROW_COUNT_MISMATCH",
  SNAPSHOT_ROW_DUPLICATE: "SNAPSHOT_ROW_DUPLICATE",
  SNAPSHOT_ROW_KEY_DUPLICATE: "SNAPSHOT_ROW_KEY_DUPLICATE",
  SNAPSHOT_ROW_KEY_UNKNOWN: "SNAPSHOT_ROW_KEY_UNKNOWN",
  SNAPSHOT_ROW_KEY_MISSING_FOR_EXISTING: "SNAPSHOT_ROW_KEY_MISSING_FOR_EXISTING",
  SNAPSHOT_IDENTITY_DUPLICATE: "SNAPSHOT_IDENTITY_DUPLICATE",
  SNAPSHOT_IDENTITY_CONFLICT: "SNAPSHOT_IDENTITY_CONFLICT",
  SNAPSHOT_INVALID_FIELD: "SNAPSHOT_INVALID_FIELD",
  SNAPSHOT_APPLY_PERMISSION_REQUIRED: "SNAPSHOT_APPLY_PERMISSION_REQUIRED",
  SNAPSHOT_MOVE_PERMISSION_REQUIRED: "SNAPSHOT_MOVE_PERMISSION_REQUIRED",
  SNAPSHOT_DISPOSAL_PERMISSION_REQUIRED: "SNAPSHOT_DISPOSAL_PERMISSION_REQUIRED",
  SNAPSHOT_RESTORE_ADMIN_REQUIRED: "SNAPSHOT_RESTORE_ADMIN_REQUIRED",
  SNAPSHOT_REASON_REQUIRED: "SNAPSHOT_REASON_REQUIRED",
  SNAPSHOT_APPROVAL_REFERENCE_REQUIRED: "SNAPSHOT_APPROVAL_REFERENCE_REQUIRED",
  SNAPSHOT_EXCLUSION_CONFIRMATION_MISMATCH: "SNAPSHOT_EXCLUSION_CONFIRMATION_MISMATCH",
  SNAPSHOT_APPLY_DISABLED: "SNAPSHOT_APPLY_DISABLED",
  SNAPSHOT_CONCURRENT_APPLY: "SNAPSHOT_CONCURRENT_APPLY"
});

export function snapshotError(code, message, extras = {}) {
  return { ok: false, code, message, ...extras };
}
